// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPo7Sy4BH6HzFwfwADEMIhLLwRvrlQvNY',
    appId: '1:462422422476:web:018b5a6e2fefdc6664e369',
    messagingSenderId: '462422422476',
    projectId: 'amr-flutter-firebase-app',
    authDomain: 'amr-flutter-firebase-app.firebaseapp.com',
    storageBucket: 'amr-flutter-firebase-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA831JNAR2jfxcU0Ek7fPEyxyVS1GI7vY',
    appId: '1:462422422476:android:0f38d7b3f95f1e7764e369',
    messagingSenderId: '462422422476',
    projectId: 'amr-flutter-firebase-app',
    storageBucket: 'amr-flutter-firebase-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWAylXaX1vgB5Eni1lyxv2Ao9_YrlFJsk',
    appId: '1:462422422476:ios:9fa3798f81c4a8f364e369',
    messagingSenderId: '462422422476',
    projectId: 'amr-flutter-firebase-app',
    storageBucket: 'amr-flutter-firebase-app.firebasestorage.app',
    iosClientId: '462422422476-41c023bh5rhuncrb7mv0n8mcdnqs20kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWAylXaX1vgB5Eni1lyxv2Ao9_YrlFJsk',
    appId: '1:462422422476:ios:9fa3798f81c4a8f364e369',
    messagingSenderId: '462422422476',
    projectId: 'amr-flutter-firebase-app',
    storageBucket: 'amr-flutter-firebase-app.firebasestorage.app',
    iosClientId: '462422422476-41c023bh5rhuncrb7mv0n8mcdnqs20kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPo7Sy4BH6HzFwfwADEMIhLLwRvrlQvNY',
    appId: '1:462422422476:web:dd3bf1a85923e63c64e369',
    messagingSenderId: '462422422476',
    projectId: 'amr-flutter-firebase-app',
    authDomain: 'amr-flutter-firebase-app.firebaseapp.com',
    storageBucket: 'amr-flutter-firebase-app.firebasestorage.app',
  );
}
